services:
  - type: web
    name: bt-phonebook-lookup
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: ADMIN_TOKEN
        generateValue: true
      - key: PDF_URLS_SOURCE
        value: file:pdf_urls.txt
      # DATABASE_URL will be set manually in Render dashboard (from Neon)
