services:
  - type: web
    name: bt-phonebook-lookup
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      # Protects /admin/reindex endpoint; Render will generate a secure random value.
      - key: ADMIN_TOKEN
        generateValue: true

      # Optional: explicit pointer to your URL list (defaults to file:pdf_urls.txt if omitted)
      - key: PDF_URLS_SOURCE
        value: file:pdf_urls.txt

      # IMPORTANT:
      # Do NOT set DATABASE_URL here if you're using Neon.
      # Instead, add DATABASE_URL in the Render web service's "Environment" tab
      # with your Neon connection string (often requires ?sslmode=require).
